[pytest]
DJANGO_SETTINGS_MODULE = ecclesia.config.settings.dev
testpaths = ecclesia/apps/users/tests/models
python_files  = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --strict-markers
    -v