# Generated by Django 6.0.5 on 2026-06-21 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_memberchurch_unique_together_and_more'),
        ('users', '0004_remove_member_contribution_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchAffiliationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('invited_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('invited_church_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('request_type', models.CharField(choices=[('invite', 'Convite'), ('request', 'Solicitação')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('expired', 'Expirado'), ('canceled', 'Cancelado'), ('waiting_registration', 'Aguardando Cadastro')], default='pending', max_length=20)),
                ('code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('mode', models.CharField(choices=[('authenticated', 'Autenticado'), ('offline', 'Offline')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('from_church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_affiliation_requests', to='users.church')),
                ('to_church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_affiliation_requests', to='users.church')),
            ],
            options={
                'verbose_name': 'Solicitação de Afiliação',
                'verbose_name_plural': 'Solicitações de Afiliação',
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_church', 'to_church', 'status'), name='unique_pending_affiliation')],
            },
        ),
    ]
