# Generated by Django 6.0.5 on 2026-06-04 21:49

import dizimus.apps.users.models.church
import dizimus.apps.users.models.user
import dizimus.apps.users.validators.validate_cep
import dizimus.apps.users.validators.validate_cpf_cnpj
import dizimus.apps.users.validators.validate_image_file
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrador Root'), ('member', 'Membro'), ('church', 'Igreja')], default='member', max_length=20, verbose_name='Tipo de usuário')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('photo', models.ImageField(blank=True, default='default/user_img.jpg', help_text='Formatos aceitos: jpg, jpeg ou png. Máx: 5MB.', null=True, upload_to=dizimus.apps.users.models.user.user_photo_path, validators=[dizimus.apps.users.validators.validate_image_file.validate_image_file])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Número de telefone no formato internacional, ex: +55 11 99999-8888.', max_length=128, region='BR')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo?')),
                ('is_trusty', models.BooleanField(default=False, verbose_name='Confiável?')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de admissão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, default='', help_text='Ex: Igreja Batista da Paz.', max_length=255, null=True, verbose_name='Nome Completo da Instituição')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Autorizado?')),
                ('cnpj', models.CharField(blank=True, help_text='Formato: 00.000.000/0000-00.', max_length=18, null=True, validators=[dizimus.apps.users.validators.validate_cpf_cnpj.validate_cnpj])),
                ('asaas_token', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Token de acesso à API do Asaas.', null=True)),
                ('total_members', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total de membros')),
                ('church_type', models.CharField(choices=[('headquarters', 'Sede/Matriz'), ('community', 'Comunidade'), ('independent', 'Independente')], default='independent', max_length=20)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Site')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('about', models.TextField(blank=True, help_text='Descrição da igreja. Máx: 1000 caracteres.', null=True, verbose_name='Sobre')),
                ('banner', models.ImageField(blank=True, default='default/banner.jpg', help_text='Formatos aceitos: jpg, jpeg ou png. Máx: 5MB.', null=True, upload_to=dizimus.apps.users.models.church.church_banner_path, validators=[dizimus.apps.users.validators.validate_image_file.validate_image_file])),
                ('parent_church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_churches', to='users.church')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='church', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
            },
        ),
        migrations.CreateModel(
            name='ChurchAddress',
            fields=[
                ('cep', models.CharField(max_length=9, validators=[dizimus.apps.users.validators.validate_cep.validar_cep], verbose_name='CEP')),
                ('road', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(max_length=10, verbose_name='N°')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('principal', models.BooleanField(default=True, verbose_name='Endereço Padrão?')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.church')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Primeiro nome')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Sobrenome')),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nome de usuário')),
                ('cpf', models.CharField(blank=True, help_text='Formato: 000.000.000-00.', max_length=14, null=True, unique=True, validators=[dizimus.apps.users.validators.validate_cpf_cnpj.validate_cpf])),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('contribution_type', models.CharField(choices=[('none', 'Nenhum'), ('dizimista', 'Dizimista'), ('ofertante', 'Ofertante'), ('both', 'Dizimista e Ofertante')], default='none', max_length=20, verbose_name='Tipo de contribuição')),
                ('date_of_birth', models.DateField(blank=True, help_text='Formato: DD/MM/AAAA.', null=True, verbose_name='Data de nascimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
        ),
        migrations.CreateModel(
            name='MemberAddress',
            fields=[
                ('cep', models.CharField(max_length=9, validators=[dizimus.apps.users.validators.validate_cep.validar_cep], verbose_name='CEP')),
                ('road', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(max_length=10, verbose_name='N°')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('principal', models.BooleanField(default=True, verbose_name='Endereço Padrão?')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.member')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='church',
            constraint=models.UniqueConstraint(fields=('cnpj', 'full_name'), name='unique_church_per_cnpj_name'),
        ),
    ]
