# Generated by Django 5.2.14 on 2026-05-28 20:54

import dizimus.apps.users.models.user
import dizimus.apps.users.validators.validate_image_file
import dizimus.config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='default/user_img.jpg', help_text='Formatos aceitos: jpg, jpeg ou png. Máx: 5MB.', null=True, storage=dizimus.config.storages.MediaFilesStorage(), upload_to=dizimus.apps.users.models.user.user_photo_path, validators=[dizimus.apps.users.validators.validate_image_file.validate_image_file]),
        ),
    ]
