# Generated by Django 5.2.14 on 2026-05-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador Root'), ('member', 'Membro'), ('church', 'Igreja')], default='member', max_length=20, verbose_name='Tipo de usuário'),
        ),
    ]
