# Generated by Django 5.2.14 on 2026-05-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberchurch',
            name='role',
            field=models.CharField(choices=[('member', 'Membro'), ('pastor/padre', 'Pastor/Padre'), ('tesoureiro', 'Tesoureiro'), ('secretário', 'Secretário'), ('admin', 'Administrador')], db_index=True, default='member', max_length=30, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='memberchurch',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('pending', 'Pendente')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='memberchurch',
            index=models.Index(fields=['church', 'role'], name='users_membe_church__18c6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='memberchurch',
            index=models.Index(fields=['church', 'status'], name='users_membe_church__5cca4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberchurch',
            constraint=models.UniqueConstraint(fields=('member', 'church'), name='unique_member_church'),
        ),
    ]
