# Generated by Django 6.0.5 on 2026-06-08 14:08

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='church',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Número de telefone no formato internacional, ex: +55 11 99999-8888.', max_length=128, region='BR'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Número de telefone no formato internacional, ex: +55 11 99999-8888.', max_length=128, region='BR'),
        ),
    ]
