# Generated by Django 6.0.5 on 2026-06-12 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='contribution_type',
        ),
    ]
