# Generated by Django 6.0.5 on 2026-07-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_member_contribution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='church_type',
            field=models.CharField(choices=[('parish', 'Paróquia'), ('community', 'Comunidade'), ('independent', 'Independente')], default='independent', max_length=20),
        ),
    ]
