# Generated by Django 6.0.5 on 2026-07-04 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_churchaffiliationrequest'),
        ('users', '0005_alter_church_church_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Ex: members.view, members.create, church.update', max_length=100, unique=True, verbose_name='Código da permissão')),
                ('name', models.CharField(help_text='Ex: Visualizar membros, Criar membros', max_length=150, verbose_name='Nome')),
                ('module', models.CharField(db_index=True, help_text='Ex: members, church, finance, events', max_length=50, verbose_name='Módulo')),
                ('description', models.TextField(blank=True, default='', help_text='Descrição detalhada do que esta permissão permite', null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Desative para remover a permissão do sistema sem deletá-la', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Permissão do Sistema',
                'verbose_name_plural': 'Permissões do Sistema',
                'ordering': ['module', 'code'],
                'indexes': [models.Index(fields=['module'], name='users_syste_module_438f78_idx'), models.Index(fields=['code'], name='users_syste_code_083d64_idx'), models.Index(fields=['module', 'is_active'], name='users_syste_module_d35ce4_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_system_permission_code')],
            },
        ),
        migrations.CreateModel(
            name='MemberChurchPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Desative para remover temporariamente esta permissão', verbose_name='Ativo')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Concedido em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Deixe em branco para permissão permanente', null=True, verbose_name='Expira em')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Concedido por')),
                ('member_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='community.memberchurch', verbose_name='Vínculo Membro-Igreja')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_church_permissions', to='users.systempermission', verbose_name='Permissão')),
            ],
            options={
                'verbose_name': 'Permissão do Membro na Igreja',
                'verbose_name_plural': 'Permissões dos Membros nas Igrejas',
                'indexes': [models.Index(fields=['member_church', 'permission'], name='users_membe_member__52c914_idx'), models.Index(fields=['member_church', 'is_active'], name='users_membe_member__559c11_idx'), models.Index(fields=['permission', 'is_active'], name='users_membe_permiss_402562_idx')],
                'constraints': [models.UniqueConstraint(fields=('member_church', 'permission'), name='unique_member_church_permission')],
            },
        ),
    ]
