# Generated by Django 6.0.5 on 2026-06-04 21:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberChurch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Membro'), ('pastor/padre', 'Pastor/Padre'), ('tesoureiro', 'Tesoureiro'), ('secretário', 'Secretário'), ('admin', 'Administrador')], db_index=True, default='member', max_length=30, verbose_name='Função')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('pending', 'Pendente')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o membro se vinculou à igreja.', verbose_name='Data de adesão')),
                ('left_at', models.DateTimeField(blank=True, help_text='Data e hora em que o membro se desvinculou da igreja. Deixe em branco se ainda for membro.', null=True, verbose_name='Data de saída')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_memberships', to='users.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_memberships', to='users.member')),
            ],
            options={
                'verbose_name': 'Vínculo Membro-Igreja',
                'verbose_name_plural': 'Vínculos Membro-Igreja',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['member', 'church'], name='community_m_member__208e90_idx'), models.Index(fields=['church', 'role'], name='community_m_church__b1cb72_idx'), models.Index(fields=['church', 'status'], name='community_m_church__14504b_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'church'), name='unique_member_church')],
                'unique_together': {('member', 'church')},
            },
        ),
    ]
