# Generated by Django 6.0.5 on 2026-06-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberchurch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='memberchurch',
            name='contribution_type',
            field=models.CharField(choices=[('none', 'Nenhum'), ('dizimista', 'Dizimista'), ('ofertante', 'Ofertante'), ('both', 'Dizimista e Ofertante')], default='none', max_length=20, verbose_name='Tipo de contribuição'),
        ),
    ]
